/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 armchair.glb 
Author: Nikolay Kudrin (https://sketchfab.com/knik211)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lounger-armchair-e9d9d87c32f144e2873765e66814f727
Title: Lounger Armchair
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ArmChair(props) {


  const { nodes, materials } = useGLTF('/models/armchair/armchair.glb')
  return (
    <group {...props} dispose={null}>
      <group  rotation={[ -1.67, 0, -2.4]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.Lounger_wire_115115115} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.Lounger_wire_115115115} />
      </group>
    </group>
  )
}

useGLTF.preload('/armchair.glb')
