/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 cream.glb 
Author: nurhadimli (https://sketchfab.com/nurhadimli)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cream-tube-8aaf1b896afb41169ab7eb8f72842cc3
Title: Cream Tube
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cream(props) {
  const { nodes, materials } = useGLTF('models/cream/cream.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.052']} position={[0.209, 0.233, 0.936]} rotation={[0, 0, Math.PI]} scale={[0.643, 0.241, 0.615]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.052']} position={[0.827, 0.368, 0.936]} rotation={[0, 0, Math.PI]} scale={[0.643, 0.354, 0.643]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.053']} position={[0.827, 0.848, 0.936]} scale={[0.639, 0.074, 0.639]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.052']} position={[0.827, 0.368, 0.936]} scale={[0.643, 0.354, 0.643]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.055']} position={[-0.513, 2.171, -1.151]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.057']} position={[0.827, 4.196, 1.817]} scale={[0.005, 0.064, 0.005]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.052']} position={[2.306, 0.169, -3.853]} rotation={[0, -0.591, -1.44]} scale={[0.643, 0.241, 0.615]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.052']} position={[2.384, 0.076, -3.795]} rotation={[0, -0.591, -2.264]} scale={[0.643, 0.354, 0.643]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['Material.053']} position={[1.732, 0.702, -4.237]} rotation={[0, -0.591, 1.701]} scale={[0.639, 0.074, 0.639]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['Material.052']} position={[2.128, 0.764, -3.972]} rotation={[0, -0.591, 1.701]} scale={[0.643, 0.354, 0.643]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Material.057']} position={[-1.514, 0.267, -5.356]} rotation={[0, -0.591, 1.701]} scale={[0.005, 0.064, 0.005]} />
    </group>
  )
}

useGLTF.preload('models/cream/cream.glb')
